/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package akka_java_sample;

import akka.http.javadsl.server.HttpApp;
import akka.http.javadsl.server.Route;

class MinimalHttpApp extends HttpApp {
    @Override
    protected Route routes() {
        return path("hello", () -> get(() -> complete("Say hello to akka-http")));
    }
}

public class App {
    public static void main(String[] args) {
        final MinimalHttpApp myServer = new MinimalHttpApp();
        try {
            myServer.startServer("localhost", 8080);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
