/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package akka_java_sample;

import org.junit.Test;

import akka.http.javadsl.model.HttpRequest;
import akka.http.javadsl.testkit.JUnitRouteTest;
import akka.http.javadsl.testkit.TestRoute;

public class AppTest extends JUnitRouteTest {
    TestRoute appRoute = testRoute(new MinimalHttpApp().routes());

    @Test
    public void testCalculatorAdd() {
        appRoute.run(HttpRequest.GET("/hello")).assertStatusCode(200).assertEntity("Say hello to akka-http");
    }
}
